name: Kitchensink

on:
  push:
    tags:
      - pyrene-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: (cd kitchensink && BASE_PATH=pyrene/ npm run build)

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./kitchensink/dist
